### ISSUE TITLE
The dataset is not available any more.

### ISSUE THREAD

**Issue by serre20** [jixuan-wang/Grad2Task#1]
Can you release the dataset again?

**Comment by Nicholas-cool** [comment]
I have the same question, i can't get the dataset, it's very disturbing.

**Comment by jixuan-wang** [comment]
https://drive.google.com/file/d/1RJK6sBXi-OoDkOs5Lm2whvCykgExdDKU/view?usp=share_link

**Comment by serre20** [comment]
Thanks
